apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default.admin
  namespace: default
spec:
  ingress:
  - from:
    - ipBlock:
        cidr: 130.211.0.0/22
    - ipBlock:
        cidr: 35.191.0.0/16
    ports:
    - protocol: TCP
      port: 8085       
  podSelector:
    matchLabels:
      app: admin
  policyTypes:
  - Ingress
