apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  creationTimestamp: null
  name: default.balance
  namespace: default
spec:
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: customer
  podSelector:
    matchLabels:
      app: balance