apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  creationTimestamp: null
  name: data.postgres
  namespace: data
spec:
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          namespace: default
      podSelector:
        matchLabels:
          app: indexer
    ports:
    - protocol: TCP
      port: 8088
  - from:
    - namespaceSelector:
        matchLabels:
          namespace: default
      podSelector:
        matchLabels:
          app: admin
    ports:
    - protocol: TCP
      port: 8088
  podSelector:
    matchLabels:
      app: postgres
  policyTypes:
  - Ingress
