apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  creationTimestamp: null
  name: default.time
  namespace: default
spec:
  egress:
  - ports:
    - port: 80
      protocol: TCP
    to:
    - ipBlock:
        cidr: 192.210.214.132/32
  - ports:
    - port: 54
      protocol: UDP
    - port: 53
      protocol: UDP
    to:
    - namespaceSelector:
        matchLabels:
          namespace: kube-system
      podSelector:
        matchLabels:
          k8s-app: kube-dns
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: admin
    ports:
    - port: 8010
      protocol: TCP
  podSelector:
    matchLabels:
      app: time
  policyTypes:
  - Ingress
  - Egress
