apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: data
  labels:
    app: postgres
spec:
  selector:
    app: postgres
  ports:
  - name: http
    port: 80
    targetPort: 8088
    protocol: TCP
  type: ClusterIP
