apiVersion: v1
kind: Namespace
metadata:
  name: data
  labels:
    namespace: data
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgres
  namespace: data
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: data
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres  
  template:
    metadata:
      labels:
        app: postgres
    spec:
      serviceAccountName: postgres
      containers:
      - name: postgres
        image: tufinim/postgres
        ports:
        - containerPort: 8088
