apiVersion: v1
kind: Service
metadata:
  name: indexer
  namespace: default
  labels:
    app: indexer
spec:
  selector:
    app: indexer
  ports:
  - name: http
    port: 9999
    targetPort: 9999
    protocol: TCP