apiVersion: v1
kind: ServiceAccount
metadata:
  name: indexer
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: indexer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: indexer  
  template:
    metadata:
      labels:
        app: indexer
    spec:
      serviceAccountName: indexer
      containers:
      - name: indexer
        image: tufinim/generic-bank-indexer
        env:
        - name: REDIS
          value: "http://redis"
        - name: POSTGRES
          value: "http://postgres.data.svc.cluster.local"
        - name: POSTGRES_USER
          value: "admin"
        - name: POSTGRES_PASSWORD
          value: "123"
        resources:
          limits:
            cpu: ".025"
          requests:
            cpu: ".025"
