apiVersion: v1
kind: Service
metadata:
  name: maintenance
  namespace: default
  labels:
    app: maintenance
spec:
  selector:
    app: maintenance
  ports:
  - name: http
    port: 80
    targetPort: 8085
    protocol: TCP