apiVersion: v1
kind: Service
metadata:
  name: customer
  namespace: default
  labels:
    app: customer
spec:
  selector:
    app: customer
  ports:
  - name: http
    port: 80
    targetPort: 8085
    protocol: TCP
  type: NodePort
