apiVersion: v1
kind: ServiceAccount
metadata:
  name: time-service-account
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: time
spec:
  replicas: 1
  selector:
    matchLabels:
      app: time
  template:
    metadata:
      labels:
        app: time
    spec:
      serviceAccountName: time-service-account
      containers:
      - name: time
        image: tufinim/generic-bank-time
        ports:
        - containerPort: 8010
        env:
        - name: TIMEZONEDB_API_KEY
          value: #TIMEZONEDB_API_KEY#
