apiVersion: v1
kind: Service
metadata:
  name: time
  namespace: default
  labels:
    app: time
spec:
  selector:
    app: time
  ports:
  - name: http
    port: 80
    targetPort: 8010
    protocol: TCP