apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: default
  labels:
    app: redis
spec:
  selector:
    app: redis
  ports:
  - name: http
    port: 80
    targetPort: 8088
    protocol: TCP
  type: ClusterIP
