apiVersion: v1
kind: ServiceAccount
metadata:
  name: redis
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis  
  template:
    metadata:
      labels:
        app: redis
    spec:
      serviceAccountName: redis
      containers:
      - name: redis
        image: tufinim/redis
        ports:
        - containerPort: 8088
        resources:
          limits:
            cpu: ".025"
          requests:
            cpu: ".025"
